### ISSUE TITLE
ErrorException - Declaration of Ccovey

### ISSUE THREAD

**Issue by joseinazusa** [ccovey/odbc-driver#12]
There is a strong chance this is a user issue, I apologize if it is
1.  Create a Brand New Laravel 4.1 project via Composer
2.  Add ccovey
   "require": {
       "laravel/framework": "4.1.*",
       "ccovey/odbc-driver-l4": "1.1.x"
   },
3.  Composer Install
4.  Replace Driver:   'Ccovey\ODBCDriver\ODBCDriverServiceProvider',
5.  Add database config.

Windows 7/64, Xampp, php 5.4

Refresh application and get the following error exception.

ErrorException
Declaration of Ccovey\ODBCDriver\ODBCDriverConnectionFactory::createConnection() should be compatible with Illuminate\Database\Connectors\ConnectionFactory::createConnection($driver, PDO $connection, $database, $prefix = '', array $config = Array)

**Comment by wstaples** [comment]
I had this error a while back to. It looks like it was fixed in this commit https://github.com/ccovey/odbc-driver/commit/98e3e4cbe265d3d386656dea4dda5eec7d19db3d

Are you pulling the latest code? maybe you just need to modify the file manually.

**Comment by joseinazusa** [comment]
I guess Laravel update didn't pull the updated code.  I manually pulled the plugin and it had the above commit.  Thank you.  Worked like a charm.
