### ISSUE TITLE
 Cannot use Illuminate\Database\Schema\Grammars\Grammar as Grammar because the name is already in use in 

### ISSUE THREAD

**Issue by andrewvmail** [ccovey/odbc-driver#15]
Having errors in running the package on laravel 4.1.X
Below is the error message, Thanks in advanced!
PHP Fatal error:  Cannot use Illuminate\Database\Schema\Grammars\Grammar as Grammar because the name is already in use in /Users/andrew/Desktop/odbc/vendor/ccovey/odbc-driver-l4/src/Ccovey/ODBCDriver/ODBCDriverConnection.php on line 5
{"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"Cannot use Illuminate\Database\Schema\Grammars\Grammar as Grammar because the name is already in use","file":"\/Users\/andrew\/Desktop\/odbc\/vendor\/ccovey\/odbc-driver-l4\/src\/Ccovey\/ODBCDriver\/ODBCDriverConnection.php"

**Comment by pa-m** [comment]
+1
as a workaround I commented out the 2nd "use ...Grammar" statement, it seems to be useless.
