### ISSUE TITLE
[Bug] getDefaultSchemaGrammar trying to instantiate inexistent class

### ISSUE THREAD

**Issue by antonioribeiro** [ccovey/odbc-driver#6]
In this portion of the code:

```
protected function getDefaultSchemaGrammar()
{
    return $this->withTablePrefix(new Schema\Grammars\Grammar);
}
```

Since there is no `Ccovey\\ODBCDriver\\Schema\\Grammars\\Grammar`, we changed it to

```
protected function getDefaultSchemaGrammar()
{
    return $this->withTablePrefix(new \Illuminate\Database\Schema\SqlServerGrammar);
}
```

And it worked fine. Sorry for not sending a PR, I don't (think I) have a database I could access via ODBC here.

**Comment by ccovey** [comment]
Thanks @antonioribeiro this is fixed in master. I need to do some cleaning up of the branches and I'll tag a release.
