### ISSUE TITLE
Problem with ODBCDriverConnection

### ISSUE THREAD

**Issue by alexrsg** [ccovey/odbc-driver#8]
I've updated the last commit and now I get a issue: Declaration of Ccovey\ODBCDriver\ODBCDriverConnectionFactory::createConnection() should be compatible with Illuminate\Database\Connectors\ConnectionFactory::createConnection($driver, PDO $connection, $database, $prefix = '', array $config = Array)

How can I fix it?

**Comment by wstaples** [comment]
Hi,
In the file vendor/ccovey/odbc-driver-l4/src/Ccovey/ODBCDriver/ODBCDriverConnectionFactory.php 

change the line: 
public function createConnection($driver, \PDO $connection, $database, $prefix ='', $config = null)

to read:
public function createConnection($driver, \PDO $connection, $database, $prefix ='', array $config = array())

I think it was line 39

**Comment by alexrsg** [comment]
Thank You!
I saw that at pull request section and change it!
It works now!
